services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: mytube
      POSTGRES_PASSWORD: mytube
    ports:
      - '10101:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: ghcr.io/jendib/mytube/api:latest
    pull_policy: always
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://mytube_db_1/mytube'
      QUARKUS_DATASOURCE_USERNAME: 'mytube'
      QUARKUS_DATASOURCE_PASSWORD: 'mytube'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GOOGLE_REFRESH_TOKEN: '${GOOGLE_REFRESH_TOKEN}'
    ports:
      - '10102:8080'

  web:
    image: ghcr.io/jendib/mytube/web:latest
    pull_policy: always
    restart: always
    environment:
      API_URL: '${API_URL}'
    ports:
      - '10103:80'

volumes:
  db: