version: '3.1'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: mytube
      POSTGRES_PASSWORD: mytube
    ports:
      - '10101:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    image: ghcr.io/jendib/mytube/api:latest
    restart: always
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: 'jdbc:postgresql://mytube_db_1/mytube'
      QUARKUS_DATASOURCE_USERNAME: 'mytube'
      QUARKUS_DATASOURCE_PASSWORD: 'mytube'
      GOOGLE_AUTH: '${GOOGLE_AUTH}'
    ports:
      - '10102:8080'
    volumes:
      - credentials:/root/.oauth-credentials

  web:
    image: ghcr.io/jendib/mytube/web:latest
    restart: always
    ports:
      - '10103:80'

volumes:
  db:
  credentials: